export const GET_TOKEN_START = 'GET_TOKEN_START';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE';

export const PAYMENT_CONNECTION_START = 'PAYMENT_CONNECTION_START';
export const PAYMENT_CONNECTION_SUCCESS = 'PAYMENT_CONNECTION_SUCCESS';
export const PAYMENT_CONNECTION_FAILURE = 'PAYMENT_CONNECTION_FAILURE';
